name: test-code

on: [ push, pull_request ]

jobs:
  test-code:
    name: ''
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
        shopware-version: [ 5.6 ]

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Cache composer
        uses: actions/cache@v2
        with:
          path: ~/vendor/
          key: php-${{ matrix.php-version }}-shopware-${{ matrix.shopware-version }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php-${{ matrix.php-version }}-shopware-${{ matrix.shopware-version }}-composer-
            php-${{ matrix.php-version }}-shopware-

      - name: Prepare composer
        run: |
          ls -la
          echo 'use finde'
          find scripts
          ./etc/scripts/prepareComposerJson.sh

      - name: Composer install
        run: composer install -n --no-progress

      - name: Check coding standards
        run: ./etc/scripts/checkCodingStandards.sh

      - name: Check plugin structure
        run: ./etc/scripts/checkForCorrectPluginStructure.sh

      - name: Check coding standards
        run: vendor/bin/phpspec-standalone.${PHP_VERSION}.phar run --no-code-generation --format=dot
